PySCIPOpt: pyscipopt.expr Namespace Reference
pyscipopt.expr Namespace Reference
Classes
class Constant
class Expr
class ExprCons
class GenExpr
class Op
class PowExpr
class ProdExpr
class SumExpr
class Term
class UnaryExpr
class VarExpr
Functions
def buildGenExprObj (expr)
def quicksum (termlist)
def quickprod (termlist)
def exp (expr)
def log (expr)
def sqrt (expr)
def expr_to_nodes (expr)
def value_to_array (val, nodes)
def expr_to_array (expr, nodes)
Variables
CONST = Term()
Operator = Op()
Function Documentation
buildGenExprObj()
def pyscipopt.expr.buildGenExprObj (expr)
helper function to generate an object of type GenExpr
Definition at line 116 of file expr.pxi.
quicksum()
def pyscipopt.expr.quicksum (termlist)
add linear expressions and constants much faster than Python's sum
by avoiding intermediate data structures and adding terms inplace
Definition at line 357 of file expr.pxi.
quickprod()
def pyscipopt.expr.quickprod (termlist)
multiply linear expressions and constants by avoiding intermediate
data structures and multiplying terms inplace
Definition at line 366 of file expr.pxi.
exp()
def pyscipopt.expr.exp (expr)
returns expression with exp-function
Definition at line 648 of file expr.pxi.
References pyscipopt.expr.buildGenExprObj().
log()
def pyscipopt.expr.log (expr)
returns expression with log-function
Definition at line 651 of file expr.pxi.
References pyscipopt.expr.buildGenExprObj().
sqrt()
def pyscipopt.expr.sqrt (expr)
returns expression with sqrt-function
Definition at line 654 of file expr.pxi.
References pyscipopt.expr.buildGenExprObj().
expr_to_nodes()
def pyscipopt.expr.expr_to_nodes (expr)
transforms tree to an array of nodes. each node is an operator and the position of the
children of that operator (i.e. the other nodes) in the array
Definition at line 658 of file expr.pxi.
References pyscipopt.expr.expr_to_array().
value_to_array()
def pyscipopt.expr.value_to_array (val, nodes)
adds a given value to an array
Definition at line 666 of file expr.pxi.
expr_to_array()
def pyscipopt.expr.expr_to_array (expr, nodes)
adds expression to array
Definition at line 676 of file expr.pxi.
References pyscipopt.expr.value_to_array().
Variable Documentation
CONST
CONST = Term()
Definition at line 113 of file expr.pxi.
Operator
Operator = Op()
Definition at line 403 of file expr.pxi.