PySCIPOpt: ssa Namespace Reference
ssa Namespace Reference
Functions
def ssa (n, h, K, f, T)
def make_data ()
def f (i, k)
Variables
z
sigma
h
T
K
n
def model = ssa(n,h,K,f,T)
x
s
L
Function Documentation
ssa()
def ssa.ssa (n, h, K, f, T)
ssa -- multi-stage (serial) safety stock allocation model
Parameters:
    - n: number of stages
    - h[i]: inventory cost on stage i
    - K: number of linear segments
    - f: (non-linear) cost function
    - T[i]: production lead time on stage i
Returns the model with the piecewise linear relation on added variables x, f, and z.
Definition at line 14 of file ssa.py.
References piecewise.convex_comb_sos(), f(), and pyscipopt.expr.quicksum().
make_data()
def ssa.make_data ()
creates example data set
Definition at line 57 of file ssa.py.
f()
def ssa.f (i, k)
Definition at line 79 of file ssa.py.
Variable Documentation
z
z
Definition at line 78 of file ssa.py.
sigma
sigma
Definition at line 78 of file ssa.py.
h
h
Definition at line 78 of file ssa.py.
T
T
Definition at line 78 of file ssa.py.
K
K
Definition at line 78 of file ssa.py.
n
n
Definition at line 78 of file ssa.py.
model
def model = ssa(n,h,K,f,T)
Definition at line 82 of file ssa.py.
x
x
Definition at line 86 of file ssa.py.
s
s
Definition at line 86 of file ssa.py.
L
L
Definition at line 86 of file ssa.py.