PySCIPOpt: logical Namespace Reference
logical Namespace Reference
Functions
def printFunc (name, m)
def and_constraint (v=1, sense="minimize")
def or_constraint (v=0, sense="maximize")
def xors_constraint (v=1)
def xorc_constraint (v=0, sense="maximize")
Variables
model = Model()
x = model.addVar("x","B")
y = model.addVar("y","B")
z = model.addVar("z","B")
r = model.addVar("r","B")
sense
n = model.addVar("n","I")
Function Documentation
printFunc()
def logical.printFunc (name, m)
prints results
Definition at line 20 of file logical.py.
and_constraint()
def logical.and_constraint (v = 1, sense = "minimize")
AND constraint
Definition at line 39 of file logical.py.
or_constraint()
def logical.or_constraint (v = 0, sense = "maximize")
OR constraint
Definition at line 50 of file logical.py.
xors_constraint()
def logical.xors_constraint (v = 1)
XOR (r as boolean) standard constraint
Definition at line 60 of file logical.py.
xorc_constraint()
def logical.xorc_constraint (v = 0, sense = "maximize")
XOR (r as variable) custom constraint
Definition at line 69 of file logical.py.
References and_constraint(), or_constraint(), pyscipopt.expr.quicksum(), and xors_constraint().
Variable Documentation
model
model = Model()
Definition at line 33 of file logical.py.
x
x = model.addVar("x","B")
Definition at line 35 of file logical.py.
y
y = model.addVar("y","B")
Definition at line 36 of file logical.py.
z
z = model.addVar("z","B")
Definition at line 37 of file logical.py.
r
bool r = model.addVar("r","B")
Definition at line 38 of file logical.py.
sense
sense
Definition at line 41 of file logical.py.
n
n = model.addVar("n","I")
Definition at line 77 of file logical.py.