PySCIPOpt: rcs Namespace Reference
rcs Namespace Reference
Functions
def rcs (J, P, R, T, p, c, a, RUB)
def make_1r ()
def make_2r ()
Variables
J
P
R
T
p
c
a
RUB
def model = rcs(J,P,R,T,p,c,a,RUB)
x
s
Function Documentation
rcs()
def rcs.rcs (J, P, R, T, p, c, a, RUB)
rcs -- model for the resource constrained scheduling problem
Parameters:
    - J: set of jobs
    - P: set of precedence constraints between jobs
    - R: set of resources
    - T: number of periods
    - p[j]: processing time of job j
    - c[j,t]: cost incurred when job j starts processing on period t.
    - a[j,r,t]: resource r usage for job j on period t (after job starts)
    - RUB[r,t]: upper bound for resource r on period t
Returns a model, ready to be solved.
Definition at line 8 of file rcs.py.
References pyscipopt.expr.quicksum().
make_1r()
def rcs.make_1r ()
creates example data set 1
Definition at line 53 of file rcs.py.
References pyscipopt.Multidict.multidict().
make_2r()
def rcs.make_2r ()
creates example data set 2
Definition at line 77 of file rcs.py.
References pyscipopt.Multidict.multidict().
Variable Documentation
J
J
Definition at line 113 of file rcs.py.
P
P
Definition at line 113 of file rcs.py.
R
R
Definition at line 113 of file rcs.py.
T
T
Definition at line 113 of file rcs.py.
p
p
Definition at line 113 of file rcs.py.
c
c
Definition at line 113 of file rcs.py.
a
a
Definition at line 113 of file rcs.py.
RUB
RUB
Definition at line 113 of file rcs.py.
model
def model = rcs(J,P,R,T,p,c,a,RUB)
Definition at line 114 of file rcs.py.
x
x
Definition at line 116 of file rcs.py.
s
s
Definition at line 116 of file rcs.py.