PySCIPOpt: mctransp Namespace Reference
mctransp Namespace Reference
Functions
def mctransp (I, J, K, c, d, M)
def make_inst1 ()
def make_inst2 ()
def make_inst3 ()
Variables
I
J
K
c
d
M
def model = mctransp(I,J,K,c,d,M)
int EPS = 1.e-6
def x = model.data
Function Documentation
mctransp()
def mctransp.mctransp (I, J, K, c, d, M)
mctransp -- model for solving the Multi-commodity Transportation Problem
Parameters:
    - I: set of customers
    - J: set of facilities
    - K: set of commodities
    - c[i,j,k]: unit transportation cost on arc (i,j) for commodity k
    - d[i][k]: demand for commodity k at node i
    - M[j]: capacity
Returns a model, ready to be solved.
Definition at line 13 of file mctransp.py.
References pyscipopt.expr.quicksum().
make_inst1()
def mctransp.make_inst1 ()
creates example data set 1
Definition at line 50 of file mctransp.py.
References pyscipopt.Multidict.multidict().
make_inst2()
def mctransp.make_inst2 ()
creates example data set 2
Definition at line 78 of file mctransp.py.
References pyscipopt.Multidict.multidict().
make_inst3()
def mctransp.make_inst3 ()
creates example data set 3
Definition at line 104 of file mctransp.py.
References pyscipopt.Multidict.multidict().
Variable Documentation
I
I
Definition at line 134 of file mctransp.py.
J
J
Definition at line 134 of file mctransp.py.
K
K
Definition at line 134 of file mctransp.py.
c
c
Definition at line 134 of file mctransp.py.
d
d
Definition at line 134 of file mctransp.py.
M
M
Definition at line 134 of file mctransp.py.
model
def model = mctransp(I,J,K,c,d,M)
Definition at line 135 of file mctransp.py.
EPS
int EPS = 1.e-6
Definition at line 141 of file mctransp.py.
x
def x = model.data
Definition at line 142 of file mctransp.py.