PySCIPOpt: bpp Namespace Reference
bpp Namespace Reference
Functions
def FFD (s, B)
def bpp (s, B)
def solveBinPacking (s, B)
def DiscreteUniform (n=10, LB=1, UB=99, B=100)
Variables
s
B
def ffd = FFD(s,B)
def bins = solveBinPacking(s,B)
Function Documentation
FFD()
def bpp.FFD (s, B)
First Fit Decreasing heuristics for the Bin Packing Problem.
Parameters:
    - s: list with item widths
    - B: bin capacity
Returns a list of lists with bin compositions.
Definition at line 16 of file bpp.py.
bpp()
def bpp.bpp (s, B)
bpp: Martello and Toth's model to solve the bin packing problem.
Parameters:
    - s: list with item widths
    - B: bin capacity
Returns a model, ready to be solved.
Definition at line 37 of file bpp.py.
References FFD(), and pyscipopt.expr.quicksum().
solveBinPacking()
def bpp.solveBinPacking (s, B)
solveBinPacking: use an IP model to solve the in Packing Problem.
Parameters:
    - s: list with item widths
    - B: bin capacity
Returns a solution: list of lists, each of which with the items in a roll.
Definition at line 82 of file bpp.py.
References FFD().
DiscreteUniform()
def bpp.DiscreteUniform (n = 10, LB = 1, UB = 99, B = 100)
DiscreteUniform: create random, uniform instance for the bin packing problem.
Definition at line 111 of file bpp.py.
Variable Documentation
s
s
Definition at line 122 of file bpp.py.
B
B
Definition at line 122 of file bpp.py.
ffd
def ffd = FFD(s,B)
Definition at line 126 of file bpp.py.
bins
def bins = solveBinPacking(s,B)
Definition at line 133 of file bpp.py.